#!/usr/bin/env python3
"""did:cow registry CLI"""

import json
import os
import sys
from pathlib import Path

import click
from dotenv import load_dotenv
from web3 import Web3

load_dotenv()

# ABI is generated by `forge build` in the repo root
_ABI_PATH = Path(__file__).parent.parent / "out" / "CowRegistry.sol" / "CowRegistry.json"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _w3():
    url = os.getenv("RPC_URL")
    if not url:
        raise click.ClickException("RPC_URL not set in .env")
    w3 = Web3(Web3.HTTPProvider(url))
    if not w3.is_connected():
        raise click.ClickException(f"Could not connect to {url}")
    return w3


def _contract(w3):
    addr = os.getenv("CONTRACT_ADDRESS")
    if not addr:
        raise click.ClickException("CONTRACT_ADDRESS not set in .env")
    if not _ABI_PATH.exists():
        raise click.ClickException(
            f"ABI not found at {_ABI_PATH} — run `forge build` first"
        )
    artifact = json.loads(_ABI_PATH.read_text())
    return w3.eth.contract(
        address=Web3.to_checksum_address(addr),
        abi=artifact["abi"],
    )


def _account(w3):
    key = os.getenv("PRIVATE_KEY")
    if not key:
        raise click.ClickException("PRIVATE_KEY not set in .env")
    return w3.eth.account.from_key(key)


def _parse_cow_did(did):
    """
    Parse did:cow:<controller>:<method>:<id...> into (controller_address, wrapped_did).

    The wrapped DID is returned without the leading 'did:' prefix, matching
    what the contract stores — e.g. 'plc:7qqsrnkn4moc2jgdxvh6aa3t' or
    'web:example.com'.
    """
    if not did.startswith("did:cow:"):
        raise click.ClickException(f"Not a did:cow DID: {did}")
    # did:cow:<address>:<method>:<id...>
    # splitting 'did:cow:ADDR:METHOD:ID' on ':' gives
    # ['did', 'cow', 'ADDR', 'METHOD', 'ID...']
    parts = did.split(":")
    if len(parts) < 5:
        raise click.ClickException(f"Invalid did:cow format: {did}")
    controller_hex = parts[2]
    wrapped_did = ":".join(parts[3:])  # e.g. 'web:example.com'
    return controller_hex, wrapped_did


def _controller_address(controller_hex):
    """Convert bare hex controller (no 0x) to checksummed address."""
    hex_str = controller_hex if controller_hex.startswith("0x") else f"0x{controller_hex}"
    return Web3.to_checksum_address(hex_str)


def _strip_did_prefix(wrapped_did):
    """Accept 'did:web:example.com' or 'web:example.com', always return the latter."""
    if wrapped_did.startswith("did:"):
        return wrapped_did[4:]
    return wrapped_did


def _send(w3, account, tx):
    tx["from"] = account.address
    tx["nonce"] = w3.eth.get_transaction_count(account.address)

    latest = w3.eth.get_block("latest")
    base_fee = latest["baseFeePerGas"]
    priority_fee = w3.to_wei(1, "gwei")
    tx["maxPriorityFeePerGas"] = priority_fee
    tx["maxFeePerGas"] = base_fee * 2 + priority_fee

    tx["gas"] = w3.eth.estimate_gas(tx)

    signed = account.sign_transaction(tx)
    txhash = w3.eth.send_raw_transaction(signed.raw_transaction)
    click.echo(f"tx:        {txhash.hex()}")
    receipt = w3.eth.wait_for_transaction_receipt(txhash)
    if receipt["status"] != 1:
        raise click.ClickException("Transaction reverted")
    click.echo(f"confirmed: block {receipt['blockNumber']}")
    return receipt


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

@click.group()
def cli():
    """did:cow registry CLI\n
    \b
    Reads from the chain using RPC_URL.
    Writes require PRIVATE_KEY (the current controller account).
    See .env.example for configuration.
    """


@cli.command()
@click.argument("did")
def resolve(did):
    """Resolve a did:cow DID to its current state.

    \b
    DID format: did:cow:<controller_address>:<method>:<id>
    Example:    did:cow:8BC101ABF5BcF8b6209FaaAD4D761C1ED14999Be:plc:7qqsrnkn4moc2jgdxvh6aa3t
    """
    controller_hex, initial_wrapped = _parse_cow_did(did)
    w3 = _w3()
    contract = _contract(w3)

    cow_hash = contract.functions.calculateCowHash(
        _controller_address(controller_hex),
        initial_wrapped,
    ).call()

    controller, wrapped_did = contract.functions.cows(cow_hash).call()

    if wrapped_did == "":
        # No on-chain state — initial values from the DID string are authoritative
        click.echo(f"status:     not yet registered on-chain")
        click.echo(f"wrapped:    did:{initial_wrapped}  (from DID)")
        click.echo(f"controller: {_controller_address(controller_hex)}  (initial)")
    elif wrapped_did == ":":
        click.echo(f"status:     deactivated")
    else:
        click.echo(f"status:     active")
        click.echo(f"wrapped:    did:{wrapped_did}")
        click.echo(f"controller: {controller}")


@cli.command("update-wrapped")
@click.argument("did")
@click.argument("new_wrapped_did")
def update_wrapped(did, new_wrapped_did):
    """Update the wrapped DID.

    \b
    NEW_WRAPPED_DID: the new wrapped DID, with or without leading 'did:'
      e.g.  web:example.com  or  did:web:example.com
    """
    controller_hex, initial_wrapped = _parse_cow_did(did)
    new_wrapped = _strip_did_prefix(new_wrapped_did)

    w3 = _w3()
    contract = _contract(w3)
    account = _account(w3)

    tx = contract.functions.updateWrappedDID(
        _controller_address(controller_hex),
        initial_wrapped,
        new_wrapped,
    ).build_transaction({})

    _send(w3, account, tx)
    click.echo(f"wrapped:    did:{new_wrapped}")


@cli.command("update-controller")
@click.argument("did")
@click.argument("new_controller")
def update_controller(did, new_controller):
    """Transfer control to a new Ethereum address.

    \b
    NEW_CONTROLLER: checksummed Ethereum address of the new controller.
    Note: setting this to the zero address is permanent (cow becomes uncontrollable).
    """
    controller_hex, initial_wrapped = _parse_cow_did(did)

    w3 = _w3()
    contract = _contract(w3)
    account = _account(w3)

    tx = contract.functions.updateController(
        _controller_address(controller_hex),
        initial_wrapped,
        Web3.to_checksum_address(new_controller),
    ).build_transaction({})

    _send(w3, account, tx)
    click.echo(f"controller: {Web3.to_checksum_address(new_controller)}")


@cli.command()
@click.argument("did")
@click.confirmation_option(prompt="Deactivation is permanent and cannot be undone. Continue?")
def deactivate(did):
    """Permanently deactivate a did:cow."""
    controller_hex, initial_wrapped = _parse_cow_did(did)

    w3 = _w3()
    contract = _contract(w3)
    account = _account(w3)

    cow_hash = contract.functions.calculateCowHash(
        _controller_address(controller_hex),
        initial_wrapped,
    ).call()

    tx = contract.functions.deactivate(cow_hash).build_transaction({})

    _send(w3, account, tx)
    click.echo("deactivated.")


if __name__ == "__main__":
    cli()
